In [ ]:
import pandas as pd
import numpy as np
import pickle
import re

In [ ]:
spotify_regional = pd.read_csv("spotify_tracks.csv")

In [ ]:
spotify_global = pd.read_csv("dataset.csv")

In [ ]:
print(spotify_regional.shape)
print(spotify_regional.columns)
spotify_regional.sample(2)

(62317, 22)
Index(['track_id', 'track_name', 'artist_name', 'year', 'popularity',
       'artwork_url', 'album_name', 'acousticness', 'danceability',
       'duration_ms', 'energy', 'instrumentalness', 'key', 'liveness',
       'loudness', 'mode', 'speechiness', 'tempo', 'time_signature', 'valence',
       'track_url', 'language'],
      dtype='object')

,track_id,track_name,artist_name,year,popularity,artwork_url,album_name,acousticness,danceability,duration_ms,...,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,track_url,language
28819,1BpvuKIG7jK5EiTp2tv5z8,King Shit,Shubh,2024,80,https://i.scdn.co/image/ab67616d0000b2733bf068...,Leo,0.301,0.794,226933.0,...,11.0,0.151,-8.350,0.0,0.0602,85.953,4.0,0.680,https://open.spotify.com/track/1BpvuKIG7jK5EiT...,Unknown
13601,5LRax02FHtexYq4j4qk542,"Dandanakka (From ""Romeo Juliet"")","D. Imman, Anirudh Ravichander",2016,0,https://i.scdn.co/image/ab67616d0000b273ba92e2...,Payanangal (Bon Voyage),0.409,0.672,260129.0,...,7.0,0.802,-3.927,0.0,0.2630,154.852,4.0,0.816,https://open.spotify.com/track/5LRax02FHtexYq4...,Tamil

In [ ]:
print(spotify_global.shape)
print(spotify_global.columns)
spotify_global.sample(2)

(114000, 21)
Index(['Unnamed: 0', 'track_id', 'artists', 'album_name', 'track_name',
       'popularity', 'duration_ms', 'explicit', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='object')

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
63093,63093,5AAaghHx8jedNGhHZkY8so,Busy Signal,PEPPERSPRAY RIDDIM,Bamm,0,176774,True,0.840,0.831,...,-1.937,1,0.3030,0.0367,0.000003,0.0703,0.884,133.424,5,j-rock
33647,33647,28IxIUK089R7nH1MmxGtBe,The Ready Set,Rock n Roll Christmas,I Don't Wanna Spend Another Christmas Without You,0,199813,False,0.676,0.699,...,-5.984,1,0.0375,0.1390,0.000000,0.1470,0.790,134.966,4,emo

In [ ]:
spotify_regional.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62317 entries, 0 to 62316
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   track_id          62317 non-null  object
 1   track_name        62317 non-null  object
 2   artist_name       62317 non-null  object
 3   year              62317 non-null  int64
 4   popularity        62317 non-null  int64
 5   artwork_url       62317 non-null  object
 6   album_name        62317 non-null  object
 7   acousticness      62317 non-null  float64
 8   danceability      62317 non-null  float64
 9   duration_ms       62317 non-null  float64
 10  energy            62317 non-null  float64
 11  instrumentalness  62317 non-null  float64
 12  key               62317 non-null  float64
 13  liveness          62317 non-null  float64
 14  loudness          62317 non-null  float64
 15  mode              62317 non-null  float64
 16  speechiness       62317 non-null  float64
 17  tempo             62317 non-null  float64
 18  time_signature    62317 non-null  float64
 19  valence           62317 non-null  float64
 20  track_url         62317 non-null  object
 21  language          62317 non-null  object
dtypes: float64(13), int64(2), object(7)
memory usage: 10.5+ MB

In [ ]:
spotify_global.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

In [ ]:
spotify_regional.isnull().sum()

track_id            0
track_name          0
artist_name         0
year                0
popularity          0
artwork_url         0
album_name          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
speechiness         0
tempo               0
time_signature      0
valence             0
track_url           0
language            0
dtype: int64

In [ ]:
spotify_global.isnull().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [ ]:
spotify_regional.duplicated().sum()

np.int64(78)

In [ ]:
spotify_regional = spotify_regional.drop_duplicates()

In [ ]:
spotify_regional.duplicated().sum()

np.int64(0)

In [ ]:
spotify_global.duplicated().sum()

np.int64(0)

In [ ]:
def clean_text(text):
    if not isinstance(text, str): #if text is not string(dataset may contain NaN, None values), then it will return an empty string
        return ""
    text = text.lower()
    #we will have to remove words like remastered, delux, live, etc.
    text = re.sub(r"\(.*?\)", "", text) #will remove everythng inside () brackets
    text = re.sub(r"\[.*?\]", "", text) #will remove everything inside [] brackets
    text = re.sub(r"[^a-z0-9\s]", "", text) #will remove everything except a-z and 0-9, used for removing punctuations, emojis, etc.
    text = re.sub(r"\s+", " ", text) #replaces extra spaces, tabs and new line with single white space
    return text.strip()

In [ ]:
df_global = spotify_global.copy()

df_global = df_global.drop(columns=["Unnamed: 0"], errors="ignore")
df_global = df_global.rename(columns={"artists": "artist_name"})

df_global = df_global.dropna(subset=[
    "track_name",
    "artist_name",
    "track_genre"
]) #drop rows where anyone of the above is missing

df_global["track_clean"] = df_global["track_name"].apply(clean_text)
df_global["artist_clean"] = df_global["artist_name"].apply(clean_text)

df_global["canonical_key"] = (
    df_global["track_clean"] + "_" + df_global["artist_clean"]
)

df_global["dataset_source"] = "global"

df_global = df_global.reset_index(drop=True) #removes old index and reassigns new 0-based index

In [ ]:
df_regional = spotify_regional.copy()

df_regional = df_regional.dropna(subset=[
    "track_name",
    "artist_name"
])

df_regional["track_clean"] = df_regional["track_name"].apply(clean_text)
df_regional["artist_clean"] = df_regional["artist_name"].apply(clean_text)

df_regional["canonical_key"] = (
    df_regional["track_clean"] + "_" + df_regional["artist_clean"]
)

df_regional["dataset_source"] = "regional"

df_regional = df_regional.reset_index(drop=True)

In [ ]:
common_columns = [
    "track_id",
    "track_name",
    "artist_name",
    "album_name",
    "popularity",
    "duration_ms",
    "explicit",
    "danceability",
    "energy",
    "key",
    "loudness",
    "mode",
    "speechiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "valence",
    "tempo",
    "time_signature",
    "track_genre",      # global only
    "language",         # regional only
    "track_url",        # regional only
    "artwork_url",      # regional only
    "canonical_key",
    "dataset_source"
]

In [ ]:
for col in common_columns:
    #if a column exist in df_regional, but is missing in df_global, then you add col in df_global and fill it with NaN
    if col not in df_global.columns:
        df_global[col] = np.nan
    #if a column exist in df_global, but is missing in df_regional, then you add col in df_regional and fill it with NaN
    if col not in df_regional.columns:
        df_regional[col] = np.nan

In [ ]:
df_combined = pd.concat(
    [df_global[common_columns], df_regional[common_columns]],
    ignore_index=True #ignores old indices and creates new ones
)
#this concatenates both datasets row wise

In [ ]:
before = len(df_combined)
#drops duplicated values. First sorts the dataset based on dataset_source(global comes first), then keeps only the first occurrence.
df_combined = (
    df_combined
    .sort_values("dataset_source")
    .drop_duplicates(subset=["canonical_key"], keep="first")
    .reset_index(drop=True)
)

after = len(df_combined)

print(f"Removed {before - after} duplicate songs")

Removed 58306 duplicate songs

In [ ]:
df_combined["dataset_source"].value_counts()

dataset_source
global      77758
regional    40174
Name: count, dtype: int64

In [ ]:
with open("df_combined.pkl", "wb") as f:
    pickle.dump(df_combined, f)

In [ ]:
with open("df_combined.pkl", "rb") as f:
    df = pickle.load(f)

In [ ]:
#splitting the dataset back because similarity is computed within a datset
df_global = df[df["dataset_source"] == "global"].reset_index(drop=True)
df_regional = df[df["dataset_source"] == "regional"].reset_index(drop=True)

print(len(df_global), len(df_regional))

77758 40174

In [ ]:
music_features = [
    "danceability",
    "energy",
    "loudness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "speechiness",
    "tempo"
]

vibe_features = [
    "valence",
    "energy",
    "danceability",
    "tempo"
]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler_music_global = StandardScaler()
scaler_vibe_global = StandardScaler()

music_matrix_global = scaler_music_global.fit_transform(
    df_global[music_features]
)

vibe_matrix_global = scaler_vibe_global.fit_transform(
    df_global[vibe_features]
)

In [ ]:
scaler_music_regional = StandardScaler()
scaler_vibe_regional = StandardScaler()

music_matrix_regional = scaler_music_regional.fit_transform(
    df_regional[music_features]
)

vibe_matrix_regional = scaler_vibe_regional.fit_transform(
    df_regional[vibe_features]
)

In [ ]:
with open("df_global.pkl", "wb") as f:
    pickle.dump(df_global, f)

with open("df_regional.pkl", "wb") as f:
    pickle.dump(df_regional, f)

with open("music_matrix_global.pkl", "wb") as f:
    pickle.dump(music_matrix_global, f)

with open("vibe_matrix_global.pkl", "wb") as f:
    pickle.dump(vibe_matrix_global, f)

with open("music_matrix_regional.pkl", "wb") as f:
    pickle.dump(music_matrix_regional, f)

with open("vibe_matrix_regional.pkl", "wb") as f:
    pickle.dump(vibe_matrix_regional, f)

In [ ]:
from google.colab import files

files.download("df_global.pkl")
files.download("df_regional.pkl")
files.download("music_matrix_global.pkl")
files.download("vibe_matrix_global.pkl")
files.download("music_matrix_regional.pkl")
files.download("vibe_matrix_regional.pkl")